apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: application-set-project-devops
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: [ "missingkey=error" ]
  generators:
    - git:
        repoURL: https://github.com/nivin/gitops-poc.git
        revision: HEAD
        directories:
          - path: argocd/examples/devops/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "project-devops"
      source:
        repoURL: https://github.com/nivin/gitops-poc.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        name: in-cluster
        namespace: 'argo-poc-devops'
      syncPolicy:
        automated:
          selfHeal: false
        syncOptions:
          - CreateNamespace=true