apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-2
  template:
    metadata:
      labels:
        app: service-2
    spec:
      containers:
        - image: ghcr.io/stefanprodan/podinfo:6.5.4
          name: service-2
          ports:
            - containerPort: 80
